### ISSUE TITLE
linting failing on clean master env

### ISSUE THREAD

**Issue by benjamincerigo** [octoenergy/tentaclio#118]
Hey octoenergy, 

I am looking at adding support for `gcs` but I am having some issues with the linting/env. 

It seems that when I create a new environment using `pipenv` and then run `make lint` I get this linting error:
```
pipenv run flake8 src
src/tentaclio/clients/http_client.py:55:40: F541 f-string is missing placeholders
```

To replicated:
```
git checkout master
pipenv --rm
pipenv sync --dev
make lint
```

I don't have any user configurations for flake8 thus I am not sure why there would be a linting error when the ci does not have one? 

Any ideas.

**Comment by benjamincerigo** [comment]
Closed due to a problem with my env.

**Comment by capitancambio** [comment]
great,  looking forward to it.
